### ISSUE TITLE
System IO Error

### ISSUE THREAD

**Issue by Nate463** [Blitznir/FFmpegAvalonia#3]
**Describe the bug**
System IO Error when creating checksums

**Expected behavior**
Complete Checksum Process 

**Screenshots**
![Screenshot from 2024-04-19 13-00-42](https://github.com/cybertron-cube/FFmpegAvalonia/assets/115868140/ad493791-7167-4835-95bb-5caf5a8d376b)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by Nate463** [comment]
This could just have been a drive or file issue. Relative part information from log:

frame=32604 fps= 49 q=21.0 size=  575488kB time=00:18:07.97 bitrate=4333.2kbits/s speed=1.65x    
frame=32628 fps= 49 q=21.0 size=  576000kB time=00:18:08.76 bitrate=4333.9kbits/s speed=1.65x    
[matroska,webm @ 0x564116e86100] Read error
    DateTime=2024-04-18T21:50:06.1102620Z
FFmpegAvalonia Information: 0 : STDERR**--/media/scenesavers/SS_4TB/UNT-CMP-IV/Box81-Preservation/UNTA_U0048-081-030.mkv: Input/output error
    DateTime=2024-04-18T21:50:19.2416711Z
FFmpegAvalonia Information: 0 : STDOUT**--frame=32644
    DateTime=2024-04-18T21:50:19.2494310Z
FFmpegAvalonia Information: 0 : Progress: 32644 frames finished (file)

**and** 

FFmpegAvalonia Information: 0 : STDERR**--[libx264 @ 0x564116e9bd80] ref B L1: 93.1%  6.9%
    DateTime=2024-04-18T21:50:19.5002802Z
FFmpegAvalonia Information: 0 : STDERR**--[libx264 @ 0x564116e9bd80] kb/s:4147.98
    DateTime=2024-04-18T21:50:19.5003030Z
FFmpegAvalonia Information: 0 : STDERR**--[aac @ 0x564116ea0200] Qavg: 2935.563
    DateTime=2024-04-18T21:50:19.5032903Z
FFmpegAvalonia Information: 0 : Process Exit Code: 0
    DateTime=2024-04-18T21:50:19.8128577Z
FFmpegAvalonia Information: 0 : File transcode, "/media/scenesavers/SS_4TB/UNT-CMP-IV/Box81-Preservation/UNTA_U0048-081-030.mkv", complete
    DateTime=2024-04-18T21:50:19.8129659Z
FFmpegAvalonia Error: 0 : An exception occurred in processing items task
Exception = "System.IO.IOException: Input/output error : '/media/scenesavers/SS_4TB/UNT-CMP-IV/Box81-Preservation/UNTA_U0048-081-030.mkv'
   at System.IO.RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Security.Cryptography.HashAlgorithm.ComputeHashAsyncCore(Stream inputStream, CancellationToken cancellationToken)
   at Cybertron.Hashing.GetChecksumAsync(String filePath, HashingAlgorithmTypes hashingAlgorithmType, CancellationToken ct)
   at Cybertron.Hashing.DirectoryHashAsync(String inputDir, String outputFilePath, String searchPattern, HashingAlgorithmTypes hashingAlgorithmType, CancellationToken ct)
   at FFmpegAvalonia.ViewModels.MainWindowViewModel.ProcessTaskItems(CancellationToken ct)
   at FFmpegAvalonia.ViewModels.MainWindowViewModel.StartQueueAsync(CancellationToken ct)"
Task type = "Checksum"
Cancel requested = "False"
    DateTime=2024-04-19T05:36:00.1743966Z

**Comment by Nate463** [comment]
This was due to a few corrupted packet fragments in the video stream of the file listed in the output above. Issue was **not** due to Avalonia. Closed
